### PR TITLE
Added Max Ghenis files to website

### PR DESCRIPTION
**Pull request by rickecon**
@jdebacker @MattHJensen. This PR adds @maxghenis' picture and bio and updates the other relevant menu structures and index pages. I just augmented Max's bio from his PyData talk. And I took his main picture .jpg from the web. Max can update these however he wants to.

Most of my changes to the `experts.html` index page are simply unifying the indent structure. Unfortunately, this is hard to see in lines 60-91. It is easier to see in the later lines. All I did on this page was add Max at the end of the second row (alphabetical order), then push Jonathan Pycroft to the third row before Weifeng.

### CODE REVIEW

**Comment by jdebacker** [comment]
Preview of Experts page:  [here](https://htmlpreview.github.io/?https://github.com/OpenRG/OpenRG.github.io/blob/364299249b27cc3cf0d209ca296e3ab42062fb11/experts.html)

Preview of Max bio page: [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/OpenRG/OpenRG.github.io/364299249b27cc3cf0d209ca296e3ab42062fb11/experts/ghenis.html)

**Comment by rickecon** [comment]
@jdebacker . I just fixed the problem in `experts.html`. There was an extra `div` in Jonathan Pycroft's cell. Let me know if this looks good to you now.

**Comment by MaxGhenis** [comment]
Thanks, looks great!

**Comment by jdebacker** [comment]
Ok - LGTM.  Merging.  Thanks @rickecon !

**Pull request merged**
