### PR TITLE
Added clients page

### PR DESCRIPTION
**Pull request by rickecon**
This PR adds a clients page with client logos and hyperlinks to their websites. I also added a `.gitignore` file because my Mac saved a `.DS_Store` file that Git wanted to track. And I updated the top bar navigation of each page to include the `Clients` page. @jdebacker @MattHJensen

### CODE REVIEW

**Comment by jdebacker** [comment]
HTML preview of new clients page [here](https://htmlpreview.github.io/?https://github.com/OpenRG/OpenRG.github.io/blob/d20c9aef5fb9b3277f4b224e8db76cf9a5741563/clients.html).

@rickecon - can you post screenshot of this page - the preview link above doesn't seem to be able to render the png files (probably because they are not committed and so the links work differently).

**Comment by rickecon** [comment]
@jdebacker I cannot get the logos to show in my preview either. I would suggest we just merge this PR. Then we can see if it needs adjusting after it is merged. I know that is a bad workflow, but I don't know how to get it to recognize these images. They're in a directory that will only exist after the PR is merged.

**Comment by jdebacker** [comment]
@rickecon You are using relative paths for the images.  If you can't see them when viewing the HTML on your machine, they won't show up when this is merged.  I would suggest looking into why they won't load locally.

**Comment by rickecon** [comment]
@jdebacker . Now it is fixed. I had a typo in the paths. Then I fixed the heights of the images so that each client box is approximately the same size. Here is a screenshot of the rendering on my local machine in my browser.
ClientsPageScreenShot

**Comment by rickecon** [comment]
Yes please.

**Comment by rickecon** [comment]
@jdebacker . Looks good. Glad to have that done. Thanks.

**Pull request merged**
